#ifndef SOURCE_CONSTANTS_HPP_
#define SOURCE_CONSTANTS_HPP_

#define PROTOCOL_ERROR_STRING std::string("ERROR")
#define PROTOCOL_MSG_STRING std::string("MSG")
#define PROTOCOL_MULTIPART_MSG_STRING std::string("MPMSG")
#define PROTOCOL_RESULT_NOT_READY_STRING std::string("RSN")
#define MAXCHARS_FOR_PROTOCOL_OVERHEAD 128
#define STATIC_MULTIPART_MESSAGE_PROTOCOL_OVERHEAD 49


#endif /* SOURCE_CONSTANTS_HPP_ */
