@echo off
set "mikeroTools=C:\Program Files (x86)\Mikero\DePboTools\bin"
set "modSource=F:\Git\DSR\Server Files\@DesolationServer\Addons"
set "deploy=F:\Git\DSR\Server Files\@DesolationServer\Addons"
set "packData=-p -x "thumbs.db,*.txt,*.h,*.dep,*.cpp,*.bak,*.bat,*.png,*.log,*.pew,*.tga" -z "*.wss,*.ogg,*.jpg,*.wav,*.fsm,*.pac,*.paa""
"%mikeroTools%\MakePbo.exe" -@=AdminTools %packData% "%modSource%\AdminTools" "%deploy%\AdminTools.pbo"
"%mikeroTools%\MakePbo.exe" -@=DesoDB %packData% "%modSource%\DesoDB" "%deploy%\DesoDB.pbo"
"%mikeroTools%\MakePbo.exe" -@=Desolation %packData% "%modSource%\Desolation" "%deploy%\Desolation.pbo"
"%mikeroTools%\MakePbo.exe" -@=EarPlugs %packData% "%modSource%\EarPlugs" "%deploy%\EarPlugs.pbo"
"%mikeroTools%\MakePbo.exe" -@=EasyMode %packData% "%modSource%\EasyMode" "%deploy%\EasyMode.pbo"
"%mikeroTools%\MakePbo.exe" -@=AntiSideChat %packData% "%modSource%\AntiSideChat" "%deploy%\AntiSideChat.pbo"
"%mikeroTools%\MakePbo.exe" -@=Jump %packData% "%modSource%\Jump" "%deploy%\Jump.pbo"
"%mikeroTools%\MakePbo.exe" -@=PluginManager %packData% "%modSource%\PluginManager" "%deploy%\PluginManager.pbo"
"%mikeroTools%\MakePbo.exe" -@=Realism %packData% "%modSource%\Realism" "%deploy%\Realism.pbo"
"%mikeroTools%\MakePbo.exe" -@=SpookyWeather %packData% "%modSource%\SpookyWeather" "%deploy%\SpookyWeather.pbo"
"%mikeroTools%\MakePbo.exe" -@=TimeModify %packData% "%modSource%\TimeModify" "%deploy%\TimeModify.pbo"
"%mikeroTools%\MakePbo.exe" -@=Zombz %packData% "%modSource%\Zombz" "%deploy%\Zombz.pbo"
"%mikeroTools%\MakePbo.exe" -@=ObjectMovement %packData% "%modSource%\ObjectMovement" "%deploy%\ObjectMovement.pbo"
exit /b